### ISSUE TITLE
Library vision and roadmap

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#531]
## Elevator pitch

Compiled brings platform and product closer, enabling delivery of highly performant component libraries through NPM which products can consume without needing to configure their build tooling.

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/6801309/106535228-da096980-6549-11eb-8679-ec403cebf0e9.png">

Products can style their app and also opt into advanced performance optimizations, for example extracting all found styles to a single atomic stylesheet.

<img width="996" alt="image" src="https://user-images.githubusercontent.com/6801309/106535237-dfff4a80-6549-11eb-80ac-16d28bcbe8b2.png">

When an application has all their first and third party styles written with Compiled we can use this information to drive consistency and decision making.

## Roadmap

- [x] CSS prop
- [x] Styled component
- [x] ClassNames component
- [x] Property static evaluation
- [x] CSS function static evaluation
- [ ] Function body static evaluation #510 
- [ ] Global component #62 
- [ ] Keyframes #14 
- [ ] Webpack plugin
- [ ] Parcel plugin
- [ ] CSS extraction #58
